### ISSUE TITLE
Lots of fp on CentOS 6

### ISSUE THREAD

**Issue by arkenoi** [videns/vulners-scanner#4]
like,

{
                        "bulletinVersion": "4.1.1-37.el7_0", 
                        "package": "samba-common-3.6.23-35.el6_8.x86_64", 
                        "bulletinPackage": "samba-common-4.1.1-37.el7_0.x86_64.rpm", 
                        "bulletinID": "CESA-2014:1008", 
                        "providedVersion": "0:3.6.23-35.el6_8", 
                        "operator": "lt", 
                        "providedPackage": "samba-common-3.6.23-35.el6_8.x86_64"
                    }
seems that it does not understand that CentOS 6 is not CentOS 7.

**Comment by videns** [comment]
Thanks for you notice. We've fixed it
